server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
            #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
#            - After=2021-04-25T12:45:09.095+08:00[Asia/Shanghai] #当前时间以后生效
#            - Before=2021-04-25T12:45:09.095+08:00[Asia/Shanghai]
#            - Between=2021-04-25T12:45:09.095+08:00[Asia/Shanghai],2021-04-25T12:45:09.095+08:00[Asia/Shanghai]
#            - Cookie=username,86150
        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
#            - Cookie=username,86150
#            - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
#             - Host=**.atguigu.com
#             - Method=GET
#             - Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/